" ============================================================================
" Netrw Directory Listing                                        (netrw v171)
"   /home/matheus/Documents/Project-Github/ansible-roles/roles/workspace
"   Sorted by      name
"   Sort sequence: [\/]$,\<core\%(\.\d\+\)\=\>,\.h$,\.c$,\.cpp$,\~\=\*$,*,\.o$,\.obj$,\.info$,\.swp$,\.bak$,\~$
"   Quick Help: <F1>:help  -:go up dir  D:delete  R:rename  s:sort-by  x:special
" ==============================================================================
../
./
defaults/
files/
handlers/
meta/
tasks/
templates/
tests/
vars/
README.md
