- name: Create a user '{{ user_name }}' with a home directory
  ansible.builtin.user:
    name: "{{ user_name }}"
    create_home: yes
    shell: /bin/bash
    groups: sudo,docker
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: ed25519
    password: "{{ user_pass }}"
    state: present

- name: Add SSH public key to authorized_keys for user '{{ user_name }}'
  ansible.builtin.authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ ssh_key }}"
    path: /home/{{ user_name }}/.ssh/authorized_keys
    manage_dir: yes

