- name: Clone git config repository
  ansible.builtin.git:
    repo: https://github.com/Matheus-git/git-config.git
    dest: /temp/git-config
    force: yes
    version: main
  become: true
  ignore_errors: yes

- name: Copy files with owner and permissions using symbolic representation
  ansible.builtin.shell:
    cmd: |
      chown -R {{ user_name }}:{{ user_name }} /temp/git-config &&
      rsync -a /temp/git-config/ /home/{{ user_name }}
  become: true

- name: Remove temporary directory
  ansible.builtin.file:
    path: /temp/git-config
    state: absent
  become: true

