- name: Install build-essentials
  ansible.builtin.apt:
    name: build-essential

- name: Install nvim
  ansible.builtin.apt:
    name: neovim
    state: latest

- name: Install htop
  ansible.builtin.apt:
    name: htop

- name: Install curl
  ansible.builtin.apt:
    name: curl

