- name: Atualização de pacotes/sistema
  import_tasks: update.yml

- name: Instalação de pacotes gerais
  import_tasks: install-packages.yml

- name: Install docker
  import_tasks: install-docker.yml

- name: Create user 'matheus'
  import_tasks: create-user.yml

- name: Nvim config
  import_tasks: nvim-config.yml


