- name: System/Package Update
  import_tasks: update.yml

- name: General Package Installation
  import_tasks: install-packages.yml

- name: Install Docker
  import_tasks: install-docker.yml

- name: Create user 'matheus'
  import_tasks: create-user.yml

- name: Nvim Configuration
  import_tasks: nvim-config.yml

- name: Git Configuration
  import_tasks: git-config.yml

