- name: Create directory nvim config
  ansible.builtin.file:
    path: /home/ansible/.config/nvim
    state: directory
    recurse: yes
    owner: ansible
    group: ansible

- name: Download config nvim
  ansible.builtin.git:
    repo: https://github.com/Matheus-git/nvim-plugins.git
    dest: /home/ansible/.config/nvim
  ignore_errors: yes

- name: Change permissions of a directory and its contents
  ansible.builtin.file:
    path: /home/ansible/.config
    mode: '0755'
    owner: ansible
    group: ansible
    recurse: yes
