- name: Create nvim config directory
  ansible.builtin.file:
    path: /home/matheus/.config/nvim
    state: directory
    owner: matheus
    group: matheus

- name: Download nvim config
  ansible.builtin.git:
    repo: https://github.com/Matheus-git/nvim-plugins.git
    dest: /home/matheus/.config/nvim
    version: main
  become: true
  ignore_errors: yes

- name: Change permissions of nvim config directory and its contents
  ansible.builtin.file:
    path: /home/matheus/.config
    mode: '0755'
    owner: matheus
    group: matheus
    recurse: yes

